# [Required]
# Basic component information
repo: central_node_ioc
organization: ad-build-test
url: https://github.com/ad-build-test/central_node_ioc
description: central_node_ioc copied from slaclab used for testing build for linuxRT software factory

# [Required]
# Continous integration
approvalRule: all
testingCriteria: all
issueTracker: github
jiraProjectKey: n/a

# [Required]
# Environments this app runs on
environments:
   - RHEL7

# [Required]
# Type of deployment
# Types: [ioc, hla, tools, matlab, pydm]
deploymentType: ioc

# [Optional] 
# Build method for building the component
# Can be a simple command like 'make'
build: make
